Frontend:
  impl: Chipyard
  clock_ratio: 8

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: DDR3
    org:
      preset: DDR3_4Gb_x8
      channel: 1
      rank: 2
    timing:
      preset: DDR3_1333H

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh